### ISSUE TITLE
tests fail with buffer wrong dimensions

### ISSUE THREAD

**Issue by dvincentwest** [ovidiopr/scattnlay#15]
System Information:
```
Ubuntu 19.10
GCC 8.3.0 (installed with apt)
Boost 1.6.7 (installed with apt)
scattnlay - installed via pip install
Python 3.7 using miniconda
```

Hi I am exploring this package, but am unable to run the tests.  For example, when I run:

`~/scattnlay/tests/python/>>> python test01.py`

it prints the error message:

```
Traceback (most recent call last):
  File "test01.py", line 72, in <module>
    terms, Qext, Qsca, Qabs, Qbk, Qpr, g, Albedo, S1, S2 = scattnlay(x, m)
  File "src/scattnlay.pyx", line 97, in scattnlay.scattnlay (src/scattnlay.cpp:2577)
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

I get a similar error when trying to run examples/calcspectra.py

```
Traceback (most recent call last):
  File "calc-spectra.py", line 62, in <module>
    mp=True
  File "../scattnlay/main.py", line 137, in scattnlay
    return scattnlay_(x, m, theta, nmax=nmax, pl=pl)
  File "src/scattnlay_mp.pyx", line 97, in scattnlay_mp.scattnlay (src/scattnlay_mp.cpp:2574)
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

**Comment by dvincentwest** [comment]
After building from source, I am able to get this working, presumably because the pip wheel is out of date.

**Comment by kostyfisik** [comment]
There was an API change, however, we tried to make it backward compatible. However, it seems we have missed somthing...  Thanks for finding this, next time I have some time for Scattnlay develpment I will try to investigate this.

**Comment by JackJacko** [comment]
I had the same issue and identified it as the complex refractive index array being 1-dimensional, i.e. (5, ). I had to numpy.tile() it to (1000, 5) to be compatible with the size array x, which is also (1000, 5).
